mklink /j "c:\users\%username%\programs\dw20server\world\computer\0" "%~dp0dist"
mklink /j "c:\users\%username%\programs\dw20server\world\computer\1" "%~dp0dist"
mklink /j "c:\users\%username%\programs\dw20server\world\computer\2" "%~dp0dist"
mklink /j "c:\users\%username%\programs\dw20server\world\computer\3" "%~dp0dist"
mklink /j "c:\users\%username%\programs\dw20server\world\computer\4" "%~dp0dist"
mklink /j "c:\users\%username%\programs\dw20server\world\computer\5" "%~dp0dist"
mklink /j "c:\users\%username%\programs\dw20server\world\computer\6" "%~dp0dist"